name: alfapos_app
description: Alfapos - POS tizimi (Flutter).
publish_to: none
version: 1.0.61+77

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  mobile_scanner: ^7.2.0
  shared_preferences: ^2.2.2
  http: ^1.2.0
  http_parser: ^4.1.0
  flutter_cache_manager: ^3.4.1
  image_picker: ^1.2.0
  file_picker: ^8.1.6
  path_provider: ^2.1.2
  html: ^0.15.5
  screenshot: ^3.0.0
  share_plus: ^12.0.1
  image: ^4.0.0
  gal: ^2.3.2
  printing: ^5.14.2
  pdf: ^3.11.3
  barcode: ^2.2.9
  esc_pos_utils_plus: ^2.0.4
  charset_converter: ^2.3.0
  flutter_svg: ^2.0.10+1
  flutter_lucide: ^1.11.0
  charset: ^2.0.1
  connectivity_plus: ^7.1.1
  url_launcher: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.14.4

flutter_launcher_icons:
  android: true
  ios: true
  image_path: assets/icons/alfapos_launcher.png
  # SVG qirralari kesilib qolmasligi uchun
  min_sdk_android: 21
  macos:
    generate: true
    image_path: assets/icons/alfapos_launcher.png
  windows:
    generate: true
    image_path: assets/icons/alfapos_launcher.png
    icon_size: 256

flutter:
  uses-material-design: true
  assets:
    - assets/
    - Untitled-1-01.png
    - Untitled-1-03.png
    - Untitled-1-08.png
    - Untitled-3-01.jpg
    - assets/branding/alfapos_logo.png
    - assets/branding/alfapos_sidebar_logo.png
    - scripts/windows_raw_print.ps1
